// import './globals.css'

export const metadata = {
    title: 'Blog Lists',
    description: 'Generated by me',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (

        <div>

            {children}
        </div>


    )
}
