
export const metadata = {
    title: 'Technology',
    description: 'Generated by me',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (

        <div>
            {children}
        </div>


    )
}
