'use client'

import 'bootstrap/dist/css/bootstrap.min.css'
import { Container, Nav, Navbar } from 'react-bootstrap'
export const metadata = {
    title: 'Admin Panel',
    description: 'Generated by me',
}
export default function AdminLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div className="d-flex min-vh-100">
                    {/* Sidebar */}
                    <div className="bg-light border-end p-3 sidebar">
                        <h4 className="mb-4" suppressHydrationWarning>Admin Panel</h4>
                        <Nav defaultActiveKey="/admin" className="flex-column">
                            <Nav.Link href="/admin">Dashboard</Nav.Link>
                            <Nav.Link href="/admin/posts">Quản lý bài viết</Nav.Link>
                            <Nav.Link href="/admin/users">Quản lý người dùng</Nav.Link>
                            <Nav.Link href="/">Về trang chính</Nav.Link>
                        </Nav>
                    </div>

                    {/* Main content */}
                    <div className="flex-grow-1">
                        {/* Navbar admin */}
                        <Navbar bg="dark" variant="dark" className="px-4">
                            <Navbar.Brand href="/admin">Admin Dashboard</Navbar.Brand>
                        </Navbar>

                        {/* Nội dung trang */}
                        <Container className="mt-4">
                            {children}
                        </Container>
                    </div>
                </div>
            </body>
        </html>
    )
}
